### ISSUE TITLE
Mismatch between desired and actual FFT size (pencil R2C)

### ISSUE THREAD

**Issue by pgrete** [spectralDNS/mpiFFT4py#11]
I've been using the slab R2C FFTs successfully for quite some time now.
However, I only used it on datasets that are in dimensions with multiples of 2.
Now, I'm trying to analyse at 2512^3 dataset.
The largest number of processes currently allowed/implemented(?) for this dataset is 16, which take way too long (and wastes a lot of resources given the core/memory requirements).

So I tried to switch to pencil decomposition and noticed that the target FFT size does not match the FFT memory footprint.
For example, using 512 cores and the following script
```
from mpi4py import MPI
import sys
import numpy as np
from mpiFFT4py.pencil import R2C

comm  = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

Res = int(sys.argv[1])

N = np.array([Res,Res,Res], dtype=int)
L = np.array([2*np.pi, 2*np.pi, 2*np.pi], dtype=float)
FFT = R2C(N, L, comm, "double", communication='Alltoallw')

print("[%03d] %d^3 FFT with shape" % (rank,Res), FFT.real_shape(), FFT.complex_shape())
```
results in the follow output
```
[000] 2512^3 FFT with shape (78, 157, 2512) (2512, 78, 78)
...
[479] 2512^3 FFT with shape (78, 157, 2512) (2512, 78, 78)
[480] 2512^3 FFT with shape (78, 157, 2512) (2512, 78, 87)
...
[511] 2512^3 FFT with shape (78, 157, 2512) (2512, 78, 87)
```

So while I ask for a 2512^3 FFT the resulting size is 2496x2512^2.
What happens to remaining cells? 
It'd probably be good if either an error message is thrown (if this layouts are not supported) or to fix the sizes.

**Comment by mikaem** [comment]
Hi Philipp
That's a tough error to reproduce! But I think you're right. This has not been implemented as far as I can recall and an error should have been raised. I will fix that (or fix it such that it is possible, not sure yet). Meanwhile, you could do as I have been doing, and move to the [mpi4py-fft](https://bitbucket.org/mpi4py/mpi4py-fft) code instead. This code can do any combination of size and process number, and it is much cleaner that mpiFFT4py, with much lesser code, and being much more generic:-)

**Comment by pgrete** [comment]
Hi Mikael,
thanks for the quick reply and the pointer to mpi4py-fft. I wasn't aware of the development (and it didn't show up in within my search engine bubble  when I was looking for alternative packages yesterday).
I'll give it a shot.

**Comment by mikaem** [comment]
Great
